FORMAT: 1A
HOST: https://api-test.enterprise.agero.com/v1/id

# Billing API

### Purpose
This document describes the Agero Support API for third party vendors who intend to consume or post data on behalf of service providers.
It includes information about the services, best practices on how to use them. This document is intended to be used as reference material 
for developers who are building applications using the API.

### Glossary

    API     Application Programming Interface 
    RSA     Roadside Assistance 
    INS     Insurance 
    JSON    JavaScript Object Notation 
    REST    Representational State Transfer

### Getting Started
This section describes the basic knowledge that readers should possess before beginning to develop using the API.

### URI Structure

https://host:port/vx/context /path

host and port define the host and port where the application lives. This is environment specific and will be communicated to clients of the API in offline mode.
context is the context of the application, in this case the "AgeroSupportAPI".

vx is the API version

vx/contextis the base path

path is the path of the resource declared in the REST interface.

For our example, in order to request a set of dispatches for a Service Provider with vendor id: 98765, client would construct the URI as follows:

HTTPS://API.AGERO.COM:80/V1/AgeroSupportAPI/Vendors/98765/Dispatches

NOTE: URLs are case sensitive and expected to be used exactly the way presented in this document.

### HTTP-based

Methods to retrieve data from the API require a GET request. Methods that submit – or create new data – require a POST. Methods that change
data require a PUT. Methods that destroy data require a DELETE. Requests to the API that require a particular HTTP method will return an error
if the request contains the incorrect method. The POST and PUT verbs are used in requests that have an HTTP body and the request data is housed 
in the HTTP request body. The GET and DELETE verbs are used in conjunction with requests that have no body. The request data is sent as query strings.
Requests that use PUT and DELETE are idempotent. This means that no matter how many times the methods are invoked, the resource state on the server
is only changed once.

### Client Registration Process
Clients who are interested in accessing the API Application need to register for a developer account on Agero’s developer portal. After a developer account 
is approved, each client will be allowed to create applications on the developer portal and request for access to a specific API to be used from the app. 
Up on Agero’s approval anApplication key and a secret code specific to the app.

Application Key is an app specific unique identifier that allows Agero’s systems to identify the client’s app making the request. The actual value of this component 
is decided individually for each client’s application by Agero up on approval of the client’s account.
While the Application Key allows the clients to identify themselves and their app to Agero’s system, the secret code allows the client to prove their identity.
Therefore, Secret code is an important piece of data and should be kept confidential. . It should not be used by more than one application nor should it be given
to other developers.

### Security

Agero Support API uses OAuth 2.0 with Client Credentials grant type for securing access to the API. Access to the API requires authentication of both the client’s 
application and the end-user on whose behalf the client’s application is trying to access the API.

##### Authentication of client’s application

It is required that the client’s application authenticate itself to the API using http basic authentication using the unique ApplicationKey &SecretCode issued at the 
time of app registration. Note that this is not the authentication of the end-user.
This means using the Authorization http header with a basic policy and a base 64 encoded {ApplicationKey} :{ SecretCode} like the example below

| Header Name | Description | Data Type | Mandatory (Y/N) | Value/Example | Note |
|:---------------|:------------------------------------------------------------------------|:-----------|:-----------------|:---------------|:-----------------------------------|
| Authorization | Base 64 encoded string of the clients Application Key &amp; SecretCode | String | Y |  | The {ApplicationKey}:{SecretCode} |


GET AgeroSupportAPI/V1/Vendors/98765/Claims HTTP /1.1
Authorization: Basic BIbmZud1NTMWRacEtuaTR3cUt2d3VieFFvdmc6QnlHOTVBYnU0cG1ORjZOcg==

The client’s application shall send the Authorization header pre-emptively in order to avoid unnecessary HTTP requests. If the Authorization header is 
missing a HTTP status 401 will be returned.

### Authentication of End-User

End-user is authenticated through user credentials (username / password) which are to be posted as part of the Authenticate request.

### Orchestration

On successful authentication of both client’s application and the end-user, AgeroSupport API platform generates an OAuth token and a refresh token.
OAuth token to be passed in all the subsequent requests using x-OAuthToken header as in the example below
POST/AgeroSupportAPI/V1/Authenticate HTTP /1.1
X-OAuthToken: bTBIbmZud1NTMWRacEtuaT
The OAuth token issued on successful authentication is short-lived which expires after 30 min from its issued date & time. However, if consumer wants
to access the API for longer than 30 minutes, consumer is expected to obtain a new OAuth Token prior to expiry using the refresh token. Following sequence
diagrams explain the process of generating token, accessing protected resources and refreshing the token.

# Group Security Token

## Create Security Token [/Authenticate]

###Description 

Used to obtain an OAuthToken by authenticating both the end-user and the application consuming the API on behalf of an end-user

###Extended Header Parameters 

Authorization

###Request Path Parameters 

n/a 

###Request Body Type 

n/a 

###Response Body Type 

Security Token

###Response Codes

    HTTP 200 : Ok
    HTTP 400 : Bad Request 
    HTTP 401 :Unauthorized 
    HTTP 403 : Forbidden 
    HTTP 404 : Not Found 
    HTTP 405 : Not Allowed 
    HTTP 500 : Internal Server Error 
    HTTP 501 : Service Unavailable Sample Request

### Create Security Token [POST]
+ Request (application/json)

    + Header
    
            Authorization: Basic bTBIbmZudMWRacEtuaTR3cUt2d==
            Accept: application/json
            
    + Body
    
                {
                    "userName":"testUser", 
                    "password":"testPassword"
                }
                
+ Response 200 (application/json)

    + Body
    
            {
                "vendorId": 1357770664300,
                "expiresIn": 1799,
                "oAuthRefreshToken": "Bnd7dvNi13nvft8nSukZnBTykPoeZcDW",
                "oAuthAccessToken": "0VuLkzDJNb0AbG4KonJZhVoooXm0",
                "refreshCount": "0" 
            }

## Refresh Security Token [/RefreshToken]

###Description 

Used to refresh the OAuth Token and get a new one.

###Extended Header Parameters 

Authorization---represents a base-64 encoded string of {ApplicationKey}:{SecretCode} 

X-OAuthRefreshToken---represents the refresh token returned at the time of token creation 

###Request Path Parameters 

n/a 

###Request Body Type 

n/a 

###Response Body Type 

Security Token

###Response Codes

    HTTP 200 : Ok
    HTTP 400 : Bad Request 
    HTTP 401 : Unauthorized 
    HTTP 403 : Forbidden 
    HTTP 404 : Not Found 
    HTTP 405 : Not Allowed 
    HTTP 500 : Internal Server Error 
    HTTP 501 : Service Unavailable Sample Request

### Refresh Security Token [GET]
+ Request ()

    + Header
    
            Authorization: Basic VU1zbTBIbmZud1NTMWRacEtuaTR3cUt2d== 
            X-OAuthRefreshToken: l5Hhx29IFP66FJR6Mo4hl7uQNdVzYCvf
            Accept: application/json
            
+ Response 200 (application/json)

    + Body
    
            { 
                "vendorId": 1357770664300, 
                "expiresIn": 1799,
                "oAuthRefreshToken": "Bnd7dvNi13nvft8nSukZnBTykPoeZcDW",
                "oAuthAccessToken": "0VuLkzDJNb0AbG4KonJZhVoooXm0",
                "refreshCount": 1
            }



# Group 21 Billing API
## 21.1 Get Claims [/BasePath/Vendors/{VendorId}/Claims?status={status}&viewType={viewType}]

###Description 

Allows the user to retrieve a set of claims for a given Vendor that match the provided selection criteria. Only claims for prior 120 
days will be returned. User can requesttwo views of claims: Summary / Detailed. Detailed view of a claim object will contain more 
information compared to summary view.

###URL(s) 

- BasePath/Vendors/{VendorId}/Claims?status=NV&viewType=summary
- BasePath/Vendors/{VendorId}/Claims?status=NV&viewType=details

###Extended Header Parameters 

X-OAuthToken---Represents the security OAuth Token returned from Authenticate operation

###Request Path Parameters 

VendorId---Represents the id of the Service Provider

###Request Query Parameters 

Status----represents the status of the claim being requested ViewType---represents the amount of data to be returned. 
Summary view vs. Detailed View

###Request Body Type 

n/a 

###Response Body Type 

ClaimDataResponse

###Response Codes

    HTTP 200 : Ok
    HTTP 400 : Bad Request 
    HTTP 401 : Unauthorized 
    HTTP 403 : Forbidden 
    HTTP 404 : Not Found 
    HTTP 405 : Not Allowed 
    HTTP 500 : Internal Server Error 
    HTTP 501 : Service Unavailable Sample Request

### Get Claims [GET]
+ Request ()

    + Header
    
            X-OAuthToken: oT6UzhzKAHm6glHiV8uAcRweMuUE 
            Accept: application/json
            
+ Response 200 (application/json)

    + Body
    
            {
                "count": "170", 
                "data": [
                {
                    "vendorID": "98765", 
                    "poNumber": "909642214",
                    "serviceType": null, 
                    "serviceDate": "2012-10-17T11:48:44",
                    "receivedDate": "0001-01-01T00:00:00",
                    "equipmentType": null,
                    "odometer": null,
                    "vin": null,
                    "milesToSite": null,
                    "milesTowed": null,
                    "memberNumber": null,
                    "memberFirstName": null,
                    "memberMiddleName": null,
                    "memberLastName": null,
                    "actualHours": null,
                    "submittedAmount": null,
                    "paidAmount": null,
                    "invoiceNumber": null,
                    "comments": null,
                    "status": null,
                    "adjustments": null,
                    "additionalCharge1Service": null,
                    "additionalCharge1Amount": null,
                    "additionalCharge2Service": null,
                    "additionalCharge2Amount": null,
                    "additionalCharge3Service": null,
                    "AdditionalCharge3Amount": null, 
                    "additionalCharge4Service": null, 
                    "additionalCharge4Amount": null,
                    "additionalCharge5Service": null,
                    "additionalCharge5Amount": null 
                } , 
                {
                    "vendorID": "98765",
                    "poNumber": "689706389", 
                    "serviceType": null,
                    "serviceDate": "2012-10-17T11:48:44",
                    "receivedDate": "0001-01-01T00:00:00", 
                    "equipmentType": null,
                    "odometer": null,
                    "vin": null,
                    "milesToSite": null,
                    "milesTowed": null,
                    "memberNumber": null,
                    "memberFirstName": null,
                    "memberMiddleName": null,
                    "memberLastName": null,
                    "actualHours": null,
                    "submittedAmount": null,
                    "paidAmount": null,
                    "invoiceNumber": null,
                    "comments": null,
                    "status": null, 
                    "adjustments": null,
                    "additionalCharge1Service": null,
                    "additionalCharge1Amount": null,
                    "additionalCharge2Service": null,
                    "additionalCharge2Amount": null,
                    "additionalCharge3Service": null,
                    "additionalCharge3Amount": null, 
                    "additionalCharge4Service": null,
                    "additionalCharge4Amount": null,
                    "additionalCharge5Service": null,
                    "additionalCharge5Amount": null 
                }
                ]
            }
            
## 21.2 Get a Claim [/Vendors/{VendorId}/Claims/{PONumber}]

###Description 

Allows the user to retrieve a single claim submitted for a given Vendor and PONumber

###URL(s) 

- BasePath/Vendors/{VendorId}/Claims/{PONumber}

###Extended Header Parameters 

X-OAuthToken –Represents the security OAuth Token returned from Authenticate operation

###Request Path Parameters 

VendorId---Represents the id of the Service Provider

###Request Query Parameters 

n/a

###Request Body Type 

n/a 

###Response Body Type 

Claim

###Response Codes

    HTTP 200 : Ok
    HTTP 400 : Bad Request 
    HTTP 401 : Unauthorized 
    HTTP 403 : Forbidden 
    HTTP 404 : Not Found 
    HTTP 405 : Not Allowed 
    HTTP 500 : Internal Server Error 
    HTTP 501 : Service Unavailable Sample Request

### Get a Claim [GET]
+ Request ()

    + Header
    
            x-OAuthToken:oT6UzhzKAHm6glHiV8uAcRweMuUE 
            Accept: application/json
            
+ Response 200 (application/json)

    + Body
    
            {
                "vendorID": "98765", 
                "poNumber": "909642214",
                "serviceType": null, 
                "serviceDate": "2012-10-17T11:48:44",
                "receivedDate": "0001-01-01T00:00:00",
                "equipmentType": null,
                "odometer": null,
                "vin": null,
                "milesToSite": null,
                "milesTowed": null,
                "memberNumber": null,
                "memberFirstName": null,
                "memberMiddleName": null,
                "memberLastName": null,
                "actualHours": null,
                "submittedAmount": null,
                "paidAmount": null,
                "invoiceNumber": null,
                "comments": null,
                "status": null,
                "adjustments": null,
                "additionalCharge1Service": null,
                "additionalCharge1Amount": null,
                "additionalCharge2Service": null,
                "additionalCharge2Amount": null,
                "additionalCharge3Service": null,
                "AdditionalCharge3Amount": null, 
                "additionalCharge4Service": null, 
                "additionalCharge4Amount": null,
                "additionalCharge5Service": null,
                "additionalCharge5Amount": null 
            }
            
## 21.3 Submit Claims [/Vendors/{VendorId}/Claims]

###Description 

Allows the consumer to post a set of claims for a given Vendor

###URL(s) 

- BasePath/Vendors/{VendorId}/Claims/{PONumber}

###Extended Header Parameters 

X-OAuthToken ---Represents the security OAuth Token returned from Authenticate operation

###Request Path Parameters 

VendorId---Represents the unique identifier of the Service Provider. VendorId of each claim
that’s being added should match this VendorId. Exception will be thrown otherwise

###Request Body Type 

Claim[]

###Response Body Type 

Error! Reference source not found.

###Response Codes

    HTTP 200 : Ok
    HTTP 400 : Bad Request 
    HTTP 401 : Unauthorized 
    HTTP 403 : Forbidden 
    HTTP 404 : Not Found 
    HTTP 405 : Not Allowed 
    HTTP 500 : Internal Server Error 
    HTTP 501 : Service Unavailable Sample Request

### Submit Claims [GET]
+ Request (application/json)

    + Header
    
               X-OAuthToken: oT6UzhzKAHm6glHiV8uAcRweMuUE 
               Accept: application/json 
               
    + Body 
    
                [ 
                { 
                    "vendorID":"98765",
                    "poNumber":"387321420",
                    "serviceType":"TOW",
                    "serviceDate":"2013-01-01",
                    "receivedDate":"2013-01-01",
                    "equipmentType":"PAR",
                    "odometer":"12345",
                    "vin":"78456124512457896",
                    "milesToSite":"5",
                    "milesTowed":"5",
                    "memberNumber":"78787878"
                    "memberFirstName":"Chris", 
                    "memberMiddleName":"H",
                    "memberLastName":"Hollywood",
                    "actualHours":"2",
                    "submittedAmount":"300",
                    "paidAmount":" ",
                    "invoiceNumber":"78456",
                    "comments":"This is a test.",
                    "status":" ",
                    "adjustments":[ 
                    { 
                        "adjustmentReason":" ", 
                        "adjustmentAmount":" " 
                    } 
                    ],
                    "additionalCharge1Service":"T",
                    "additionalCharge1Amount":"80.00",
                    "additionalCharge2Service":"S",
                    "additionalCharge2Amount":"100.00",
                    "additionalCharge3Service":" ",
                    "additionalCharge3Amount":" ",
                    "additionalCharge4Service":" ",
                    "additionalCharge4Amount":" ", 
                    "additionalCharge5Service":" ", 
                    "additionalCharge5Amount":" " 
                },
                {
                    "vendorID":"98765",
                    "poNumber":"387321423", 
                    "serviceType":"TOW",
                    "serviceDate":"2013-01-10",
                    "receivedDate":"2013-01-10", 
                    "equipmentType":"PAR",
                    "odometer":"12345",
                    "vin":"78456124543457896",
                    "milesToSite":"5",
                    "milesTowed":"5",
                    "memberNumber":"78657878",
                    "memberFirstName":"James",
                    "memberMiddleName":"P",
                    "memberLastName":"Estillow",
                    "actualHours":"1",
                    "submittedAmount":"200",
                    "paidAmount":" ",
                    "invoiceNumber":"78123",
                    "comments":"",
                    "status":" ",
                    "adjustments":[
                    { 
                        "adjustmentReason":" ", 
                        "adjustmentAmount":" " 
                    }
                    ], 
                    "additionalCharge1Service":"T",
                    "additionalCharge1Amount":"80.00",
                    "additionalCharge2Service":"S",
                    "additionalCharge2Amount":"100.00",
                    "additionalCharge3Service":" ",
                    "additionalCharge3Amount":" ",
                    "additionalCharge4Service":" ",
                    "additionalCharge4Amount":" ", 
                    "additionalCharge5Service":" ",
                    "additionalCharge5Amount":" "
                } ]

+ Response 200 (application/json)

    + Body
    
            {
                "count":60, 
                "numberOfSuccess":50,
                "numberOfFailure":10,
                "data":
                [ 
                    { 
                        "vendorID": "98765", 
                        "poNumber": "387321420", 
                        "status": "NV",
                        "responseMessage": "This claim has been processed previously."
                    }, 
                    {
                        "vendorID": "98765", 
                        "poNumber": "387321423", 
                        "status": "NV",
                        "responseMessage": "This claim has been processed previously."
                    } 
                ]
            }
            
            
## 21.5 Get Checks [/Vendors/{VendorId}/Checks?viewType={viewType}&startDate={startDate}&endDate={endDate}]

###Description 

Allows the consumer to retrieve a set of checks for a given vendor that matches the provided selection .
Consumer can request two views of checks: Summary view / Detailed view. Detailed view of a check object
will contain more information compared to summary view. Consumer is also required to filter the checks 
with in a certain date range

###URL(s) 

- asePath/Vendors/{VendorId}/Checks?viewType={viewType}&startDate={startDate}&endDate={endDate}
- BasePath/Vendors/{vendorId}/Checks?&viewType={viewType}&checkNumber={checkNumber}&poNumber={poNumber}&invoiceNumber={invoiceNumber}&submitDate={submitDate}&serviceDate={serviceDate}&paymentDate={paymentDate}

###Extended Header Parameters 

X-OAuthToken ---Represents the security OAuth Token returned from Authenticate operation

###Request Path Parameters 

VendorId---Represents the unique identifier of the Service Provider

###Request Query Parameters 

ViewType---Indicates if the user wants summary / detailed view of the check.Possible values are : summary / details 

StartDate---represents the start date of the date range in mm-dd-yyyy format.The Start Date shall be limited to 90 days prior to the request date. 
This is applicable if and only if view type is summary. If StartDate is provided for viewType=details, it will be ignored. 

EndDate---represents the end date of the date range in mm-dd-yyyy format. This is applicable if and only if view type is summary. 

CheckNumber---represents the unique check# associated with the check. This is applicable if and only if view type is details. If EndDate is provided
for viewType=details, it will be ignored. 

PONumber--- represents the po# associated with the check. This is applicable if and only if view type is details. 

InvoiceNumber--- represents the invoice# associated with the check. This is applicable if and only if view type is details. 

SubmitDate--- represents the date the check was submitted in mm-dd-yyyy format. This is applicable if and only if view type is details. 

ServiceDate--- represents the date check was serviced in mm-dd-yyyy format. This is applicable if and only if view type is details.

PaymentDate--- represents the date check was paid in mm-dd-yyyy format. This is applicable if and only if view type is details.

###Request Body Type 

n/a

###Response Body Type 

CheckResponse

###Response Codes

    HTTP 200 : Ok
    HTTP 400 : Bad Request 
    HTTP 401 : Unauthorized 
    HTTP 403 : Forbidden 
    HTTP 404 : Not Found 
    HTTP 405 : Not Allowed 
    HTTP 500 : Internal Server Error 
    HTTP 501 : Service Unavailable Sample Request

### Get Checks [GET]
+ Request ()

    + Header
    
               x-OAuthToken: oT6UzhzKAHm6glHiV8uAcRweMuUE 
               Accept: application/json

+ Response 200 (application/json)

    + Body
    
            { 
                "count": "170", 
                "data": 
                [ 
                { 
                    "vendorID": "98765", 
                    "checkNumber": "4953931", 
                    "poNumber": null, 
                    "invoiceNumber": null, 
                    "checkDate": "2012-12-11T12:52:32", 
                    "serviceDate": "0001-01-01T00:00:00", 
                    "submitDate": "0001-01-01T00:00:00", 
                    "amount": "268", 
                    "numberOfCalls": "7", 
                    "status": "Paid", 
                    "adjustments": null 
                }, 
                { 
                    "vendorID": "98765", 
                    "checkNumber": "4953841", 
                    "poNumber": null, 
                    "invoiceNumber": null, 
                    "checkDate": "2012-12-07T12:17:20", 
                    "serviceDate": "0001-01-01T00:00:00", 
                    "submitDate": "0001-01-01T00:00:00", 
                    "amount": "753", 
                    "numberOfCalls": "6", 
                    "status": "Paid", 
                    "adjustments": null 
                }, 
                { 
                    "vendorID": "98765", 
                    "checkNumber": "4953833", 
                    "poNumber": null, 
                    "invoiceNumber": null, 
                    "checkDate": "2012-12-05T17:04:08", 
                    "serviceDate": "0001-01-01T00:00:00", 
                    "submitDate": "0001-01-01T00:00:00", 
                    "amount": "378.75", 
                    "numberOfCalls": "6", 
                    "status": "Paid", 
                    "adjustments": null 
                }, 
                { 
                    "vendorID": "98765", 
                    "checkNumber": "5998974", 
                    "poNumber": null, 
                    "invoiceNumber": null, 
                    "checkDate": "2012-12-03T08:18:57", 
                    "serviceDate": "0001-01-01T00:00:00", 
                    "submitDate": "0001-01-01T00:00:00", 
                    "amount": "1016", 
                    "numberOfCalls": "23", 
                    "status": "Paid", 
                    "adjustments": null 
                } 
                ] 
            ] 

## 21.6 Get Paid Claims [/Vendors/{VendorId}/PaidClaims?startDate={startDate}&endDate={endDate}]

###Description 

Allows the consumer to retrieve a set of claims for a given vendor that were paid with a certain date range provided by StartDate & EndDate.

###URL(s) 

- BasePath/Vendors/{VendorId}/PaidClaims?startDate={startDate}&endDate={endDate}

###Extended Header Parameters 

X-OAuthToken ---Represents the security OAuth Token returned from Authenticate operation

###Request Path Parameters 

VendorId---Represents the unique identifier of the Service Provider

###Request Query Parameters 

StartDate--- StartDate (mm-dd-yyyy) of the date range to be used for filtering paid claims. The Start Date shall be 
limited to18 months days prior to the request date. 

EndDate---- EndDate(mm-dd-yyyy) of the date range to be used for filtering paid claims

###Request Body Type 

n/a

###Response Body Type 

ClaimDataResponse

###Response Codes

    HTTP 200 : Ok
    HTTP 400 : Bad Request 
    HTTP 401 : Unauthorized 
    HTTP 403 : Forbidden 
    HTTP 404 : Not Found 
    HTTP 405 : Not Allowed 
    HTTP 500 : Internal Server Error 
    HTTP 501 : Service Unavailable Sample Request

### Get Paid Claims [GET]
+ Request ()

    + Header
    
            X-OAuthToken: oT6UzhzKAHm6glHiV8uAcRweMuUE 
            Accept: application/json

+ Response 200 (application/json)

    + Body
    
            { 
                "count": "170", 
                "data": [ 
                { 
                    "vendorID": "98765", 
                    "poNumber": "655614813", 
                    "serviceType": "Towing", 
                    "serviceDate": "2012-12-13T00:00:00", 
                    "receivedDate": "2012-12-20T00:00:00", 
                    "equipmentType": "Primary Towing", 
                    "odometer": "12345", 
                    "vin": "78456124512457896", 
                    "milesToSite": "5", 
                    "milesTowed": "5", 
                    "memberNumber": "", 
                    "memberFirstName": "", 
                    "memberMiddleName": "", 
                    "memberLastName": "SMITH", 
                    "actualHours": "1", 
                    "submittedAmount": " $300.00", 
                    "paidAmount": " $113.00", 
                    "invoiceNumber": "78456", 
                    "comments": null, 
                    "status": "Paid", 
                    "adjustments": 
                    [ 
                    { 
                        "adjustmentReason": "Adjusted to your Rates - Audit", 
                        "adjustmentAmount": "82" 
                    }, 
                    { 
                        "adjustmentReason": "Adjusted Toll Charges", 
                        "adjustmentAmount": "55" 
                    } 
                    , 
                    { 
                        "adjustmentReason": "Storage Charges Not Authorized", 
                        "adjustmentAmount": "50" 
                    } 
                    ], 
                        "additionalCharge1Service": "Tolls ", 
                        "additionalCharge1Amount": " $80.00", 
                        "additionalCharge2Service": "Storage ", 
                        "additionalCharge2Amount": " $100.00", 
                        "additionalCharge3Service": null, 
                        "AdditionalCharge3Amount": null, 
                        "additionalCharge4Service": null, 
                        "additionalCharge4Amount": null, 
                        "additionalCharge5Service": null, 
                        "additionalCharge5Amount": null 
                }, 
                { 
                    "vendorID": "98765",  
                    "poNumber": "655614813", 
                    "serviceType": "Towing", 
                    "serviceDate": "2012-12-13T00:00:00", 
                    "receivedDate": "2012-12-20T00:00:00", 
                    "equipmentType": "Primary Towing", 
                    "odometer": "12345", 
                    "vin": "78456124512457896", 
                    "milesToSite": "5", 
                    "milesTowed": "5", 
                    "memberNumber": "", 
                    "memberFirstName": "", 
                    "memberMiddleName": "", 
                    "memberLastName": "SMITH", 
                    "actualHours": "1", 
                    "submittedAmount": " $300.00", 
                    "paidAmount": " $113.00", 
                    "invoiceNumber": "78456", 
                    "comments": null, 
                    "status": "Paid", 
                    "adjustments": 
                    [ 
                    { 
                        "adjustmentReason": "Adjusted to your Rates - Audit", 
                        "adjustmentAmount": "82" 
                    } 
                    ], 
                    "additionalCharge1Service": "Tolls ", 
                    "additionalCharge1Amount": " $80.00", 
                    "additionalCharge2Service": "Storage ", 
                    "additionalCharge2Amount": " $100.00", 
                    "additionalCharge3Service": null, 
                    "AdditionalCharge3Amount": null, 
                    "additionalCharge4Service": null, 
                    "additionalCharge4Amount": null, 
                    "additionalCharge5Service": null, 
                    "additionalCharge5Amount": null 
                } 
                ]
            }

## 21.7 Get a Paid Claim [/Vendors/{VendorId}/PaidClaims/{PONumber}]

###Description 

Allows the consumer to retrieve a paid claim for a given Vendor and a PO number. Claim will be returned only
if it was processed within 18 months prior to the request date.

###URL(s) 

- BasePath/Vendors/{VendorId}/PaidClaims/{PONumber}

###Extended Header Parameters 

X-OAuthToken ---Represents the security OAuth Token returned from Authenticate operation

###Request Path Parameters 

VendorId---Represents the unique identifier of the Service Provider 

PONumber---Represents the PO# associated with the claim

###Request Query Parameters 

n/a

###Request Body Type 

n/a

###Response Body Type 

Claim

###Response Codes

    HTTP 200 : Ok
    HTTP 400 : Bad Request 
    HTTP 401 : Unauthorized 
    HTTP 403 : Forbidden 
    HTTP 404 : Not Found 
    HTTP 405 : Not Allowed 
    HTTP 500 : Internal Server Error 
    HTTP 501 : Service Unavailable Sample Request

###Get a Paid Claim [GET]
+ Request ()

    + Header
    
            X-OAuthToken: oT6UzhzKAHm6glHiV8uAcRweMuUE
            Accept: application/json

+ Response 200 (application/json)

    + Body
    
            { 
                "vendorID": "98765", 
                "poNumber": "655614813", 
                "serviceType": "Towing", 
                "serviceDate": "2012-12-13T00:00:00", 
                "receivedDate": "2012-12-20T00:00:00", 
                "equipmentType": "Primary Towing", 
                "odometer": "12345", 
                "vin": "78456124512457896", 
                "milesToSite": "5", 
                "milesTowed": "5", 
                "memberNumber": "", 
                "memberFirstName": "", 
                "memberMiddleName": "", 
                "memberLastName": "SMITH", 
                "actualHours": "1", 
                "submittedAmount": " $300.00", 
                "paidAmount": " $113.00", 
                "invoiceNumber": "78456", 
                "comments": null, 
                "status": "Paid", 
                "adjustments": 
                [ 
                { 
                    "adjustmentReason": "Adjusted to your Rates - Audit", 
                    "adjustmentAmount": "82" 
                }, 
                { 
                    "adjustmentReason": "Adjusted Toll Charges", 
                    "adjustmentAmount": "55" 
                } 
                , 
                { 
                    "adjustmentReason": "Storage Charges Not Authorized", 
                    "adjustmentAmount": "50" 
                } 
                ], 
                "additionalCharge1Service": "Tolls ", 
                "additionalCharge1Amount": " $80.00", 
                "additionalCharge2Service": "Storage ", 
                "additionalCharge2Amount": " $100.00", 
                "additionalCharge3Service": null, 
                "additionalCharge3Amount": null, 
                "additionalCharge4Service": null, 
                "additionalCharge4Amount": null, 
                "additionalCharge5Service": null, 
                "additionalCharge5Amount": null 
            }  

# Group 7 Vendor API

## 7.10 Get List of Dispatchers [/vendors/{vendorId}/dispatchers?onDuty={true|false}]

###Description

The "Get List of Dispatchers" API will allow client app to display the list of dispatchers along with 
dispatcher info such as name, phone number, email,and picture for a given vendor.

Pagination is supported by this resource.

###Request Parameters

|Schema Property |Description   |Is Required   |Type   |Business Rules|
|:---------------|:-------------|:-------------|:------|:-------------|
|onDuty|   Represents the availability  mode of Dispatcher   |No   |Boolean|If not provided, all the dispatchers  (onDuty/offDuty) will be returned   |  

###Sample Request URL

/vendors/5447/dispatchers?onDuty=true


###Response JSON


|Schema Property |Description   |Is Required   |Type   |Business Rules|
|:---------------|:-------------|:-------------|:------|:-------------| 
|dispatcherList|   List of Dispatchers   |YES   |Dispatcher[]|

###Errors 

|HTTP Code |HTTP Reason Phrase|Error Code | Message |Reason  | 
|:---------|:-----------------|:----------|:--------|:--------|
|401       |Unauthorized      |INVALID_TOKEN| oauth.v2.InvalidAccessToken: Invalid access token |A valid OAuth token was not provided| 
|404       | No Dispatchers Found|             |  |Drivers did not exist in the database for the current request| 
|500       | Server Error     |UNKNOWN      |Unknown Error   |An unknown error occurred at the server|


###Get List of Dispatchers [GET]

+ Request ()

    + Header

            Authorization: Bearer 7z9ZeGyweG98YMAyB0iSm2EiB6bD
            
+ Response 200 (application/json)

    + Body
    
            [
                {
                    "dispatcherId" : "132454",
                    "name" : "Joe Smith",
                    "officePhone":"781-555-4321",
                    "officeEmail":"joes@gbb.com",
                    "profilePictureUrl":"/vendors/53240/dispatchers/132454/picture",
                    "profileLastUpdatedAt":"2013-01-31 08:30 AM",
                    "onDuty":true
                },
                {
                    "dispatcherId" : "4234234",
                    "name" : "Gary Smith",
                    "officePhone":"781-555-1234",
                    "officeEmail":"gsmith@gbb.com",
                    "profilePictureUrl":"/vendors/53240/dispatchers/4234234/picture",
                    "profileLastUpdatedAt":"2013-01-31 08:30 AM",
                    "onDuty":true
                }
            ]
            
            
## 7.11 Get a Dispatcher [/vendors/{vendorId}/dispatchers/{dispatcherId}]

###Description

The"Get a dispatcher" API returns dispatcher information for a dispatcher identified by a dispatcherId.
This API will allow client app to display dispatcher info such as name, phone number, email, and picture 
for a given dispatcher.

###Sample Request URL

/vendors/5447/dispatchers/235235235


###Response JSON

|Schema Property |Description   |Is Required   |Type   |Business Rules|
|:---------------|:-------------|:-------------|:------|:-------------| 
|Dispatcher|   Dispatcher identified by  the unique DispatcherId|YES   |Dispatcher|

   
###Sample Response
HTTP 201 Resource Created

###Errors 

|HTTP Code |HTTP Reason Phrase|Error Code | Message |Reason  | 
|:---------|:-----------------|:----------|:--------|:--------|
|401       |Unauthorized      |INVALID_TOKEN| oauth.v2.InvalidAccessToken: Invalid access token |A valid OAuth token was not provided| 
|404       | Resource Not Found |NO_DISPATCHER_FOUND |No Dispatcher found     |Drivers did not exist in the database for the current request| 
|404       | Resource Not Found|NO_VENDOR_FOUND|  |Drivers did not exist in the database for the current request| 
|500       | Server Error     |UNKNOWN      |Unknown Error   |An unknown error occurred at the server|


###Get a Dispatcher [GET]

+ Request ()

    + Header

            Authorization: Bearer 7z9ZeGyweG98YMAyB0iSm2EiB6bD
            
+ Response 200 (application/json)

    + Body
    
            {
                "dispatcherId" : "235235235",
                "name" : "Joe Smith",
                "officePhone":"781-555-4321",
                "officeEmail":"jsmith@gbb.com",
                "profilePictureUrl":"/vendors/53240/dispatchers/235235235/picture"
            }

# Group 12 Enumerations API
## 12.30 Get   Territories [/enumerations/territories] 

###Description

This API allows the consumer to retrieve a list of possible territories.

###Sample Request URL

/enumerations/territories

###Request Parameters

N/A

###Request Schema

N/A

###Sample Request Body 

GET https://api-test.enterprise.agero.com/v1/id/enumerations/territories
Host: api-test.enterprise.agero.com

###Sample Response

HTTP/1.1 200 Ok

###Response JSON

| Schema Property|Description   |Is Required |Type|Business Rules|
|:---------------|:-------------|:-------------|:-------------|:-------------|   
|  |  |  |  KeyValuePair [ ]|

###Errors 

|HTTP Code |Error Code | Message |Reason  | 
|:---------|:--------- |:--------|:--------|
|401       |INVALID_TOKEN| oauth.v2.InvalidAccessToken: Invalid access token |A valid OAuth token was not provided| 
|404       |RESOURCE NOT FOUND |No Vendor found |No vendor exists   in the system for the given vendorId| 
|500       | SERVER ERROR        |Unknown Error   |An unknown error occurred at the server|

###Get   Territories [GET]

+ Request ()

    + Header

            Authorization: Bearer 7z9ZeGyweG98YMAyB0iSm2EiB6bD

+ Response 200 ()

  + Body
            
            [ 
            {
                    "code": "All",
                    "value": "%"
                    },
                    {
                    "code": "Performance Advantage",
                    "value": "Performance Advantage"
                    },
                    {
                    "code": "Assigned",
                    "value": "Assigned"
                    },
                    {
                    "code": "Not Assigned",
                    "value": "Non-Assigned"
            }
            ]

## 12.31 Service Types [/enumerations/serviceTypes] 

###Description

The "Get Service Types" API provides a list of services a dispatch could be assigned for to a Service Provider.

###Sample Request URL

/enumerations/ serviceTypes.

###Request JSON

N/A

###Sample Request Body

N/A

###Repsonse JSON

| Schema Property|Description   |Is Required |Type|Business Rules|
|:---------------|:-------------|:-------------|:-------------|:-------------|   
|  |   Array of service types    |YES   |  ServiceType[]|

  
###Errors 

|HTTP Code |Error Code | Message |Reason  | 
|:---------|:--------- |:--------|:--------|
|401       |INVALID_TOKEN| oauth.v2.InvalidAccessToken: Invalid access token |A valid OAuth token was not provided| 
|500       | SERVER ERROR        |Unknown Error   |An unknown error occurred at the server|

    
### Get Service Types [GET]

+ Request ()

    + Header

            Authorization: Bearer 7z9ZeGyweG98YMAyB0iSm2EiB6bD

+ Response 200 ()

  + Body
             
             [
                {
                "code" : "1",
                "description" : "Door Unlock"
                },
                {
                "code" : "2",
                "description" : "Fuel Delivery"
                },
                {
                "code" : "3",
                "description" : "Jump Start"
                },
                {
                "code" : "4",
                "description" : "Flat Tire"
                },
                {
                "code" : "5",
                "description" : "Winch"
                },
                {
                "code" : "6",
                "description" : "Reunite"
                },
                {
                "code" : "8",
                "description" : "Tow"
                }
                ]

## 12.32 Get Equipment Types [/enumerations/equipmentTypes] 

###Description

The "Get User Role Types" API provides a list of Roles that can be assigned to a user.

###Sample Request URL

/enumerations/equipmentShiftTypes

###Request JSON

N/A

###Sample Request Body

N/A

###Repsonse JSON

| Schema Property|Description   |Is Required |Type|Business Rules|
|:---------------|:-------------|:-------------|:-------------|:-------------|   
|  | Array of equipment shift types  |YES   | equipmentShiftType[]|

###Errors 

|HTTP Code |Error Code | Message |Reason  | 
|:---------|:--------- |:--------|:--------|
|401       |INVALID_CLIENT| Client identifier is required|An API key was not supplied  | 
|404       |Resource Not Found| NO_VENDOR_FOUND |No vendor exists in the system for the given vendorId| 
|500       | SERVER ERROR        |Unknown Error   |An unknown error occurred at the server|



###Get Equipment Types [GET]

+ Request ()

    + Header

            Authorization: Bearer 7z9ZeGyweG98YMAyB0iSm2EiB6bD


+ Response 200 ()

  + Body
             
            [
                {
               
                "code" : "5WT", "description" : "5th Wheel Transport"
                },
                {
                "code" : "HDLB",
                "description" : "Heavy Duty Lowboy/Flatbed"
                },
                {
                "code" : "HDRS",
                "description" : "Heavy Duty Roadservice "
                },
                {
                "code" : "HDTS",
                "description" : "Heavy Duty Tireservice"
                },
                {
                "code" : "HDUR",
                "description" : "Heavy Duty Underreach"
                },
                {
                "code" : "HDW",
                "description" : "Heavy Duty Wrecker"
                },
                {
                "code" : "LDF",
                "description" : "Light Duty Flatbed"
                },
                { "code" : "LDWL",
                "description" : "Light Duty Wheel Lift"
                },
                {
                "code" : "LRS",
                "description" : "Lockout Roadservice"
                },
                {
                "code" : "MDF",
                "description" : "Medium Duty Flatbed"
                },
                {
                "code" : "MDRS",
                "description" : "Medium Duty Roadservice"
                },
                {
                "code" : "MDTS",
                "description" : "Medium Duty Tireservice"
                },
                {
                "code" : "MDUR",
                "description" : "Medium Duty Underreach"
                },
                {
                "code" : "MDW",
                "description" : "Medium Duty Wrecker"
                },
                {
                "code" : "MRS",
                "description" : "Minor Roadservice"
                },
                {
                "code" : "MM",
                "description" : "Mobile Mechanic"
                },
                {
                "code" : "MP",
                "description" : "Motorcycle Pickup"
                },
                {
                "code" : "MS",
                "description" : "Motorcycle Service"
                }
                ]

## 12.33 Get   Cities [/enumerations/cities?serviceProviderId={serviceProviderId}] 

###Description

This API allows the consumer to retrieve a list of cities.

###Sample Request URL

enumerations/cities?serviceProviderId=98765


###Request Parameters

| Schema Property|Description   |Is Required |Type|Business Rules|
|:---------------|:-------------|:-------------|:-------------|:-------------|   
|serviceProviderId  |Represents the unique identifier   of the service provider   |YES   |  string|

###Request Schema

N/A

###Sample Request Body 

GET https://api-test.enterprise.agero.com/v1/id/enumerations/cities?serviceProviderId=98765
Host: api-test.enterprise.agero.com

###Sample Response          

HTTP/1.1 200 Ok

###Response JSON

| Schema Property|Description   |Is Required |Type|Business Rules|
|:---------------|:-------------|:-------------|:-------------|:-------------|   
|  | |   |  KeyValuePair [ ]|

###Errors 

|HTTP Code |HTTP Reason Phrase|Error Code | Message |Reason  | 
|:---------|:----------------|:----------|:--------|:--------|
|400       | Invalid Request     | INVALID_SERVICEPROVIDERID | serviceProviderId  is missing | No serviceProviderId  is provided| 
|401       |Unauthorized      |INVALID_TOKEN| oauth.v2.InvalidAccessToken: Invalid access token |A valid OAuth token was not provided| 
|404       | Resource Not Found  |  NO_VENDOR_FOUND    |   No Vendor found  |   No vendor exists  in the system for the given vendorId| 
|500       | Server Error     |UNKNOWN      |Unknown Error   |An unknown error occurred at the server|



###Get   Cities [GET]

+ Request ()

    + Header

            Authorization: Bearer 7z9ZeGyweG98YMAyB0iSm2EiB6bD

+ Response 200 ()

  + Body
            
            [
                {
                "code": "ADDISON,TX",
                "value": "'ADDISON,TX'"
                },
                {
                "code": "ALLEN,TX",
                "value": "'ALLEN,TX'"
                },
                {
                "code": "ALVORD,TX",
                "value": "'ALVORD,TX'"
                },
                {
                "code": "ARGYLE,TX",
                "value": "'ARGYLE,TX'"
                },
                {
                "code": "ARLINGTON,TX",
                "value": "'ARLINGTON,TX'"
                },
                {
                "code": "AUBREY,TX",
                "value": "'AUBREY,TX'"
                },
                {
                "code": "AURORA,TX",
                "value": "'AURORA,TX'"
                },
                {
                "code": "BARTONVILLE,TX",
                "value": "'BARTONVILLE,TX'"
                },
                {
                "code": "BAY CITY,TX",
                "value": "'BAY CITY,TX'"
                }
                ]


## 12.34 Get   Vendor Info [/enumerations/vendorInfo] 


###Description

This API allows the consumer to retrieve a list of states for a given service providers.

###Sample Request URL

/enumerations/vendorInfo


###Request Parameters

N/A
                         
###Request Schema

N/A

###Sample Request Body 

GET https://api-test.enterprise.agero.com/v1/id/enumerations/vendorInfo
Host: api-test.enterprise.agero.com

###Sample Response

HTTP/1.1 200 Ok

###Response JSON

| Schema Property|Description   |Is Required |Type|Business Rules|
|:---------------:|:-------------|:-----------|:---------------|:-------------|   
|                |              |            |  KeyValuePair[ ]  |
 
###Errors 

|HTTP Code |HTTP Reason Phrase|Error Code | Message |Reason  | 
|:---------|:----------------|:----------|:--------|:-------|
|401       |Unauthorized      |INVALID_TOKEN| oauth.v2.InvalidAccessToken: Invalid access token |A valid OAuth token was not provided| 
|404       | Resource Not Found  |  NO_VENDOR_FOUND    |   No Vendor found  |   No vendor exists  in the system for the given vendorId| 
|500       | Server Error     |UNKNOWN      |Unknown Error   |An unknown error occurred at the server|




###Get   Vendor Info [GET]

+ Request ()

    + Header

            Authorization: Bearer 7z9ZeGyweG98YMAyB0iSm2EiB6bD

+ Response 200 ()

  + Body
            
            [
                {
                "code": "Billing",
                "value": "Billing"
                },
                {
                "code": "Facility",
                "value": "Facility"
                },
                {
                "code": "Insurance",
                "value": "Insurance"
                },
                {
                "code": "Equipment",
                "value": "Equipment"
                },
                {
                "code": "Rates",
                "value": "Rates"
                },
                {
                "code": "Territories",
                "value": "Territories"
                }
                ]


## 12.35 Get  Claim Ranges [/enumerations/claimRanges] 

###Description

This API allows the consumer to retrieve the claim ranges.

###Sample Request URL

/enumerations/claimRanges


###Request Parameters

N/A
                         
###Request Schema

N/A

###Sample Request Body 

GET https://api-test.enterprise.agero.com/v1/id/enumerations/claimRanges
Host: api-test.enterprise.agero.com

###Sample Response

HTTP/1.1 200 Ok

###Response JSON

| Schema Property|Description   |Is Required |Type|Business Rules|
|:---------------|:-------------|:-----------|:---------------|:-------------|   
|                |              |            |  KeyValuePair[ ]  |



###Errors 

|HTTP Code |HTTP Reason Phrase|Error Code | Message |Reason  | 
|:---------|:----------------|:----------|:--------|:--------|
|401       |Unauthorized      |INVALID_TOKEN| oauth.v2.InvalidAccessToken: Invalid access token |A valid OAuth token was not provided| 
|404       | Resource Not Found  |  NO_VENDOR_FOUND    |   No Vendor found  |   No vendor exists  in the system for the given vendorId| 
|500       | Server Error     |UNKNOWN      |Unknown Error   |An unknown error occurred at the server|



###Get Claim Ranges [GET]

+ Request ()

    + Header

            Authorization: Bearer 7z9ZeGyweG98YMAyB0iSm2EiB6bD

+ Response 200 ()

  + Body
            
            [
                {
                "code": "All",
                "value": ""
                },
                {
                "code": "Greater Than",
                "value": ">"
                },
                {
                "code": "Greater Than or Equal To",
                "value": ">="
                },
                {
                "code": "Less Than",
                "value": "<"
                },
                {
                "code": "Less Than or Equal To",
                "value": "<="
                },
                {
                "code": "Equals",
                "value": "="
                }
                ]

## 12.36 Get  ETA Ranges [/enumerations/etaRanges] 


###Description

This API allows the consumer to retrieve the etaRanges.

###Sample Request URL

/enumerations/etaRanges


###Request Parameters

N/A
                         
###Request Schema

N/A

###Sample Request Body 

GET https://api-test.enterprise.agero.com/v1/id/enumerations/etaRanges
Host: api-test.enterprise.agero.com

###Sample Response

HTTP/1.1 200 Ok

###Response JSON

| Schema Property|Description  |Is Required|Type|Business Rules|
|:--------------|:-------------|:----------|:---|:-------------|   
|                |              |          |KeyValuePair[ ]|

###Errors 

|HTTP Code |HTTP Reason Phrase|Error Code | Message |Reason  | 
|:---------|:----------------|:----------|:--------|:--------|
|401       |Unauthorized      |INVALID_TOKEN| oauth.v2.InvalidAccessToken: Invalid access token |A valid OAuth token was not provided| 
|404       | Resource Not Found  |  NO_VENDOR_FOUND    |   No Vendor found  |   No vendor exists  in the system for the given vendorId| 
|500       | Server Error     |UNKNOWN      |Unknown Error   |An unknown error occurred at the server|



###Get ETA Ranges [GET]

+ Request ()

    + Header

            Authorization: Bearer 7z9ZeGyweG98YMAyB0iSm2EiB6bD

+ Response 200 ()

  + Body
            
            [
                {
                "code": "All",
                "value": "%"
                },
                {
                "code": "1 to 15 minutes",
                "value": "1,16"
                },
                {
                "code": "16 to 30 minutes",
                "value": "16,31"
                },
                {
                "code": "31 to 45 minutes",
                "value": "31,46"
                }
                ]


## 12.37 CallAcceptanceFlags [/enumerations/callAcceptanceFlags] 

###Description

This API allows the consumer to retrieve a list of possible call acceptance flags.   

###Sample Request URL

/enumerations/callAcceptanceFlags

###Request Parameters

N/A

###Request Schema

N/A

###Sample Request Body

GET https://api-test.enterprise.agero.com/v1/id/enumerations/callAcceptanceFlags
Host: api-test.enterprise.agero.com

###Response JSON

| Schema Property|Description  |Is Required|Type|Business Rules|
|:--------------|:-------------|:----------|:---|:-------------|   
|               |||KeyDescriptionPair [ ]||

###Errors 

|HTTP Code |HTTP Reason Phrase|Error Code | Message |Reason  | 
|:---------|:----------------|:----------|:--------|:--------|
|401       |Unauthorized      |INVALID_TOKEN| oauth.v2.InvalidAccessToken: Invalid access token |A valid OAuth token was not provided| 
|404       | Resource Not Found     |NO_VENDOR_FOUND      |No Vendor found |No vendor exists in the system for the given vendorId|
|500       | Server Error     |UNKNOWN      |Unknown Error   |An unknown error occurred at the server|



### CallAcceptanceFlags [GET]

+ Request ()

    + Header

            Authorization: Bearer 7z9ZeGyweG98YMAyB0iSm2EiB6bD

+ Response 200 (application/json)

    + Body
            
            HTTP/1.1 200 Ok
            [
            {
            "code": "ALL",
            "description": "All"
            },
            {
            "code": "RFSD",
            "description": "Refused"
            },
            {
            "code": "ACCPTD",
            "description": "Accepted"
            }
            ]


## 12.38 Get  ETA Met [/enumerations/etaMet] 

###Description

This API allows the consumer to retrieve a list of possible ETA Met values. 

###Sample Request URL

/enumerations/etaMet


###Request Parameters

N/A
                         
###Request Schema

N/A

###Sample Request Body 

GET https://api-test.enterprise.agero.com/v1/id/enumerations/etaMet
Host: api-test.enterprise.agero.com

###Sample Response

HTTP/1.1 200 Ok

###Response JSON

| Schema Property|Description  |Is Required|Type|Business Rules|
|:--------------|:-------------|:----------|:---|:-------------|   
|                |              |          |KeyValuePair[ ]|

###Errors 

|HTTP Code |HTTP Reason Phrase|Error Code | Message |Reason  | 
|:---------|:----------------|:----------|:--------|:--------|
|401       |Unauthorized      |INVALID_TOKEN| oauth.v2.InvalidAccessToken: Invalid access token |A valid OAuth token was not provided| 
|404       | Resource Not Found  |  NO_VENDOR_FOUND    |   No Vendor found  |   No vendor exists  in the system for the given vendorId| 
|500       | Server Error     |UNKNOWN      |Unknown Error   |An unknown error occurred at the server|



###Get ETA Met [GET]

+ Request ()

    + Header

            Authorization: Bearer 7z9ZeGyweG98YMAyB0iSm2EiB6bD

+ Response 200 ()

  + Body
            
            [
                {
                "code": "All",
                "value": "%"
                },
                {
                "code": "Refused",
                "value": "0"
                },
                {
                "code": "Accepted",
                "value": "1"
                },
                {
                "code": "NA", 
                "description": "N/A" 
                }

                ]





## 12.39 Get  Claim Status Codes [/enumerations/claimStatusCodes] 


###Description

This API allows the consumer to retrieve a list of possible Claim Status Codes. 

###Sample Request URL

/enumerations/claimStatusCodes


###Request Parameters

N/A
                         
###Request Schema

N/A

###Sample Request Body 

GET https://api-test.enterprise.agero.com/v1/id/enumerations/claimStatusCodes
Host: api-test.enterprise.agero.com

###Sample Response

HTTP/1.1 200 Ok

###Response JSON

| Schema Property|Description  |Is Required|Type|Business Rules|
|:--------------|:-------------|:----------|:---|:-------------|   
|                |              |          |KeyValuePair[ ]|

###Errors 

|HTTP Code |HTTP Reason Phrase|Error Code | Message |Reason  | 
|:---------|:----------------|:----------|:--------|:--------|
|401       |Unauthorized      |INVALID_TOKEN| oauth.v2.InvalidAccessToken: Invalid access token |A valid OAuth token was not provided| 
|404       | Resource Not Found  |  NO_VENDOR_FOUND    |   No Vendor found  |   No vendor exists  in the system for the given vendorId| 
|500       | Server Error     |UNKNOWN      |Unknown Error   |An unknown error occurred at the server|




###Get Claim Status Codes [GET]

+ Request ()

    + Header

            Authorization: Bearer 7z9ZeGyweG98YMAyB0iSm2EiB6bD

+ Response 200 (application/json)

    + Body
   
            [
            {
            "code": "NV",
            "description": "Not submitted yet"
            },
            {
            "code": "VE",
            "description": "Successfully submitted"
            },
            {
            "code": "VO",
            "description": "Service Date is more than 90 days old"
            },
            {
            "code": "VA",
            "description": "Chose the PO from the dropdown and submitted"
            },
            {
            "code": "PD",
            "description": "Paid"
            } ,
            {
            "code": "%",
            "description": "All"
            }
            ]

            
            
            
## Get  Request Status [/enumerations/requestStatusCodes] 


###Description

This API allows the consumer to retrieve a list of possible request Status Codes. 

###Sample Request URL

/enumerations/requestStatusCodes


###Request Parameters

N/A
                         
###Request Schema

N/A

###Sample Request Body 

GET https://api-test.enterprise.agero.com/v1/id/enumerations/requestStatusCodes
Host: api-test.enterprise.agero.com

###Sample Response

        HTTP/1.1 200 Ok
        [
        {
        "code": "1",
        "description": "Added"
        },
        {
        "code": "2",
        "description": "Updated"
        },
        {
        "code": "3",
        "description": "Deleted"
        }
        ]

###Response JSON

| Schema Property|Description  |Is Required|Type|Business Rules|
|:--------------|:-------------|:----------|:---|:-------------|   
|                |              |          |EnumerationType[ ]|

###Errors 

|HTTP Code |HTTP Reason Phrase|Error Code | Message |Reason  | 
|:---------|:----------------|:----------|:--------|:--------|
|401       |Unauthorized      |INVALID_TOKEN| oauth.v2.InvalidAccessToken: Invalid access token |A valid OAuth token was not provided| 
|500       | Server Error     |UNKNOWN      |Unknown Error   |An unknown error occurred at the server|




###Get Request Status [GET]

+ Request ()

    + Header

            Authorization: Bearer 7z9ZeGyweG98YMAyB0iSm2EiB6bD

+ Response 200 (application/json)

    + Body
            
            [
            {
            "code": "1",
            "description": "Added"
            },
            {
            "code": "2",
            "description": "Updated"
            },
            {
            "code": "3",
            "description": "Deleted"
            }
            ]
            
            
##Get  Vendor Request Status Codes [/enumerations/vendorRequestStatusCodes] 


###Description

This API allows the consumer to retrieve a list of possible request Status Codes for Vendor Entities. 

###Sample Request URL

/enumerations/vendorRequestStatusCodes


###Request Parameters

N/A
                         
###Request Schema

N/A

###Sample Request Body 

GET https://api-test.enterprise.agero.com/v1/id/enumerations/ vendorRequestStatusCodes
Host: api-test.enterprise.agero.com

###Sample Response

        HTTP/1.1 200 Ok
        [
        {
        "code": "PND",
        "description": "Pending"
        },
        {
        "code": "UNDRVW",
        "description": "UnderReview"
        },
        {
        "code": "APPRVD",
        "description": "Approved"
        },
        {
        "code": "DECLND",
        "description": "Declined"
        }
        ]

###Response JSON

| Schema Property|Description  |Is Required|Type|Business Rules|
|:--------------|:-------------|:----------|:---|:-------------|   
|                |              |          |EnumerationType[ ]|

###Errors 

|HTTP Code |HTTP Reason Phrase|Error Code | Message |Reason  | 
|:---------|:----------------|:----------|:--------|:--------|
|401       |Unauthorized      |INVALID_TOKEN| oauth.v2.InvalidAccessToken: Invalid access token |A valid OAuth token was not provided| 
|500       | Server Error     |UNKNOWN      |Unknown Error   |An unknown error occurred at the server|




###Get Request Status [GET]

+ Request ()

    + Header

            Authorization: Bearer 7z9ZeGyweG98YMAyB0iSm2EiB6bD

+ Response 200 (application/json)

    + Body
            
            
            [
            {
            "code": "PND",
            "description": "Pending"
            },
            {
            "code": "UNDRVW",
            "description": "UnderReview"
            },
            {
            "code": "APPRVD",
            "description": "Approved"
            },
            {
            "code": "DECLND",
            "description": "Declined"
            }
            ]
            

            
            
## 12.40 Get  Zip Codes [/enumerations/zipCodes?serviceProviderId={serviceProviderId}] 


###Description

This API allows the consumer to retrieve a list of zip codes for a given Service Provider. 

###Sample Request URL

/enumerations/zipCodes?serviceProviderId=98765


###Request Parameters

| Schema Property|Description  |Is Required|Type|Business Rules|
|:--------------|:-------------|:----------|:---|:-------------|   
|serviceProviderId|Represents the unique identifier of the service provider|Yes|string|

###Request Schema

N/A

###Sample Request Body 

GET https://api-test.enterprise.agero.com/v1/id/enumerations/zipCodes?serviceProviderId=98765
Host: api-test.enterprise.agero.com

###Sample Response

HTTP/1.1 200 Ok

###Response JSON

| Schema Property|Description  |Is Required|Type|Business Rules|
|:--------------|:-------------|:----------|:---|:-------------|   
|                |              |          |KeyValuePair[ ]|

###Errors 

|HTTP Code |HTTP Reason Phrase|Error Code | Message |Reason  | 
|:---------|:----------------|:----------|:--------|:--------|
|400       | Invalid Request      |INVALID_ SERVICEPROVIDERID|serviceProviderId is missing|No serviceProviderId is provided| 
|401       |Unauthorized      |INVALID_TOKEN| oauth.v2.InvalidAccessToken: Invalid access token |A valid OAuth token was not provided| 
|404       | Resource Not Found  |  NO_VENDOR_FOUND    |   No Vendor found  |   No vendor exists  in the system for the given vendorId| 
|500       | Server Error     |UNKNOWN      |Unknown Error   |An unknown error occurred at the server|



###Get Zip Codes [GET]

+ Request ()

    + Header

            Authorization: Bearer 7z9ZeGyweG98YMAyB0iSm2EiB6bD

+ Response 200 (application/json)

    + Body
            
            [
                {
                "code": "01904",
                "value": "01904"
                },
                {
                "code": "44143",
                "value": "44143"
                },
                {
                "code": "75001",
                "value": "75001"
                },
                {
                "code": "75002",
                "value": "75002"
                },
                {
                "code": "75006",
                "value": "75006"
                },
                {
                "code": "75007",
                "value": "75007"
                }
                ]      
                
                
                
## 12.41 Get  Service Equipments [/enumerations/serviceEquipments?serviceProviderId={serviceProviderId}] 


###Description

This API allows the consumer to retrieve a list of service equipments for a given Service Provider.

###Sample Request URL

/enumerations/serviceEquipments?serviceProviderId=98765


###Request Parameters

| Schema Property|Description  |Is Required|Type|Business Rules|
|:--------------|:-------------|:----------|:---|:-------------|   
|serviceProviderId|Represents the unique identifier of the service provider|Yes|string|

###Request Schema

N/A

###Sample Request Body 

GET https://api-test.enterprise.agero.com/v1/id/enumerations/serviceEquipments?serviceProviderId=98765
Host: api-test.enterprise.agero.com

###Sample Response

HTTP/1.1 200 Ok

###Response JSON

| Schema Property|Description  |Is Required|Type|Business Rules|
|:--------------|:-------------|:----------|:---|:-------------|   
|                |              |          |KeyValuePair[ ]|

###Errors 

|HTTP Code |HTTP Reason Phrase|Error Code | Message |Reason  | 
|:---------|:----------------|:----------|:--------|:--------|
|400       | Invalid Request      |INVALID_ SERVICEPROVIDERID|serviceProviderId is missing|No serviceProviderId is provided| 
|401       |Unauthorized      |INVALID_TOKEN| oauth.v2.InvalidAccessToken: Invalid access token |A valid OAuth token was not provided| 
|404       | Resource Not Found  |  NO_VENDOR_FOUND    |   No Vendor found  |   No vendor exists  in the system for the given vendorId| 
|500       | Server Error     |UNKNOWN      |Unknown Error   |An unknown error occurred at the server|



###Get Service Equipments [GET]

+ Request ()

    + Header

            Authorization: Bearer 7z9ZeGyweG98YMAyB0iSm2EiB6bD

+ Response 200 (application/json)

    + Body
            
            [
            {
            "code": "Dolly Wheels",
            "value": "Dolly Wheels"
            },
            {
            "code": "Heavy Duty Undereach",
            "value": "Heavy Duty Undereach"
            },
            {
            "code": "Heavy Duty Wrecker",
            "value": "Heavy Duty Wrecker"
            },
            {
            "code": "Light Duty Flatbed",
            "value": "Light Duty Flatbed"
            },
            {
            "code": "Light Duty Mobile Mechanic",
            "value": "Light Duty Mobile Mechanic"
            },
            {
            "code": "Light Duty Wheel Lift",
            "value": "Light Duty Wheel Lift"
            },
            {
            "code": "Lockout Roadservice",
            "value": "Lockout Roadservice"
            }
            ]
            
            
## 12.42 Get  Survey Scores [/enumerations/surveyStores?serviceProviderId={serviceProviderId}] 

###Description

This API allows the consumer to retrieve a list of servey stores for a given Service Provider.

###Sample Request URL

/enumerations/surveyStores?serviceProviderId=98765


###Request Parameters

| Schema Property|Description  |Is Required|Type|Business Rules|
|:--------------|:-------------|:----------|:---|:-------------|   
|serviceProviderId|Represents the unique identifier of the service provider|Yes|string|


###Request Schema

N/A

###Sample Request Body 

GET https://api-test.enterprise.agero.com/v1/id/enumerations/surveyStores?serviceProviderId=98765
Host: api-test.enterprise.agero.com

###Sample Response

HTTP/1.1 200 Ok

###Response JSON

| Schema Property|Description  |Is Required|Type|Business Rules|
|:--------------|:-------------|:----------|:---|:-------------|   
|                |              |          |KeyValuePair[ ]|

###Errors 


|HTTP Code |HTTP Reason Phrase|Error Code | Message |Reason  | 
|:---------|:----------------|:----------|:--------|:--------|
|400       | Invalid Request      |INVALID_ SERVICEPROVIDERID|serviceProviderId is missing|No serviceProviderId is provided| 
|401       |Unauthorized      |INVALID_TOKEN| oauth.v2.InvalidAccessToken: Invalid access token |A valid OAuth token was not provided| 
|404       | Resource Not Found  |  NO_VENDOR_FOUND    |   No Vendor found  |   No vendor exists  in the system for the given vendorId| 
|500       | Server Error     |UNKNOWN      |Unknown Error   |An unknown error occurred at the server|
  


###Get Survey Scores [GET]

+ Request ()

    + Header

            Authorization: Bearer 7z9ZeGyweG98YMAyB0iSm2EiB6bD

+ Response 200 (application/json)

    + Body
            
            [
            {
            "code": "Excellent",
            "value": "4"
            },
            {
            "code": "Good",
            "value": "3"
            },
            {
            "code": "Fair",
            "value": "2"
            },
            {
            "code": "Poor",
            "value": "1"
            }
            ]
            
## 12.43 Get  Call Details [/enumerations/callDetails] 

###Description

This API allows the consumer to retrieve a list of call details.

###Sample Request URL

/enumerations/callDetails


###Request Parameters

N/A 

###Request Schema

N/A

###Sample Request Body 

GET https://api-test.enterprise.agero.com/v1/id/enumerations/callDetails
Host: api-test.enterprise.agero.com

###Sample Response

HTTP/1.1 200 Ok

###Response JSON

| Schema Property|Description  |Is Required|Type|Business Rules|
|:--------------|:-------------|:----------|:---|:-------------|   
|                |              |          |KeyValuePair[ ]|

###Errors 


|HTTP Code |HTTP Reason Phrase|Error Code | Message |Reason  | 
|:---------|:----------------|:----------|:--------|:--------|
|401       |Unauthorized      |INVALID_TOKEN| oauth.v2.InvalidAccessToken: Invalid access token |A valid OAuth token was not provided| 
|404       | Resource Not Found  |  NO_VENDOR_FOUND    |   No Vendor found  |   No vendor exists  in the system for the given vendorId| 
|500       | Server Error     |UNKNOWN      |Unknown Error   |An unknown error occurred at the server|

  


###Get Call Details [GET]

+ Request ()

    + Header

            Authorization: Bearer 7z9ZeGyweG98YMAyB0iSm2EiB6bD

+ Response 200 (application/json)

    + Body
            
            [
                {
                "code": "Cancelled",
                "value": "Cancelled"
                },
                {
                "code": "Claims Payment Issue",
                "value": "Claims Payment Issue"
                },
                {
                "code": "Customer - Bad experience",
                "value": "Customer - Bad experience"
                },
                {
                "code": "Customer - Preference",
                "value": "Customer - Preference"
                },
                {
                "code": "Discontinued Services",
                "value": "Discontinued Services"
                },
                {
                "code": "GOA",
                "value": "GOA"
                },
                {
                "code": "Lack of Equipment",
                "value": "Lack of Equipment"
                },
                {
                "code": "No Direct Contact - Busy",
                "value": "No Direct Contact - Busy"
                }
                ]
            
## 12.44 Get  Service Categories [/enumerations/serviceCategories?serviceProviderId={serviceProviderId}] 

###Description

This API allows the consumer to retrieve a list of service categories for a given Service Provider.

###Sample Request URL

/enumerations/serviceCategories?serviceProviderId=98765


###Request Parameters

| Schema Property|Description  |Is Required|Type|Business Rules|
|:--------------|:-------------|:----------|:---|:-------------|   
|serviceProviderId|Represents the unique identifier of the service provider|Yes|string|

###Request Schema

N/A

###Sample Request Body 

GET https://api-test.enterprise.agero.com/v1/id/enumerations/serviceCategories?serviceProviderId=98765
Host: api-test.enterprise.agero.com

###Sample Response

HTTP/1.1 200 Ok

###Response JSON

| Schema Property|Description  |Is Required|Type|Business Rules|
|:--------------|:-------------|:----------|:---|:-------------|   
|                |              |          |KeyValuePair[ ]|

###Errors 

|HTTP Code |HTTP Reason Phrase|Error Code | Message |Reason  | 
|:---------|:----------------|:----------|:--------|:--------|
|400       | Invalid Request      |INVALID_ SERVICEPROVIDERID|serviceProviderId is missing|No serviceProviderId is provided| 
|401       |Unauthorized      |INVALID_TOKEN| oauth.v2.InvalidAccessToken: Invalid access token |A valid OAuth token was not provided| 
|404       | Resource Not Found  |  NO_VENDOR_FOUND    |   No Vendor found  |   No vendor exists  in the system for the given vendorId| 
|500       | Server Error     |UNKNOWN      |Unknown Error   |An unknown error occurred at the server|

   


###Get Service Categories [GET]

+ Request ()

    + Header

            Authorization: Bearer 7z9ZeGyweG98YMAyB0iSm2EiB6bD

+ Response 200 (application/json)

    + Body
            
            [
                {
                "code": "Heavy Duty Road",
                "value": "Heavy Duty Road"
                },
                {
                "code": "Heavy Duty Tow",
                "value": "Heavy Duty Tow"
                },
                {
                "code": "Light Duty Road",
                "value": "Light Duty Road"
                },
                {
                "code": "Light Duty Tow",
                "value": "Light Duty Tow"
                },
                {
                "code": "Locksmith",
                "value": "Locksmith"
                },
                {
                "code": "Medium Duty Road",
                "value": "Medium Duty Road"
                },
                {
                "code": "Medium Duty Tow",
                "value": "Medium Duty Tow"
                },
                {
                "code": "Motorcycle",
                "value": "Motorcycle"
                },
                {
                "code": "Other",
                "value": "Other"
                },
                {
                "code": "Priority/Accident Management",
                "value": "Priority/Accident Management"
                },
                {
                "code": "Secondary/Release Management",
                "value": "Secondary/Release Management"
                }
                ]
                
                
## 12.45 Get  States [/enumerations/states?serviceProviderId={serviceProviderId}] 

###Description

This API allows the consumer to retrieve a list of states for a given Service Provider.

###Sample Request URL

/enumerations/states?serviceProviderId=98765


###Request Parameters

| Schema Property|Description  |Is Required|Type|Business Rules|
|:--------------|:-------------|:----------|:---|:-------------|   
|serviceProviderId|Represents the unique identifier of the service provider|Yes|string|

 
###Request Schema

N/A

###Sample Request Body 

GET https://api-test.enterprise.agero.com/v1/id/enumerations/states?serviceProviderId=98765
Host: api-test.enterprise.agero.com

###Sample Response

HTTP/1.1 200 Ok

###Response JSON

| Schema Property|Description  |Is Required|Type|Business Rules|
|:--------------|:-------------|:----------|:---|:-------------|   
|                |              |          |KeyValuePair[ ]|

###Errors 

|HTTP Code |HTTP Reason Phrase|Error Code | Message |Reason  | 
|:---------|:----------------|:----------|:--------|:--------|
|400       | Invalid Request      |INVALID_ SERVICEPROVIDERID|serviceProviderId is missing|No serviceProviderId is provided| 
|401       |Unauthorized      |INVALID_TOKEN| oauth.v2.InvalidAccessToken: Invalid access token |A valid OAuth token was not provided| 
|404       | Resource Not Found  |  NO_VENDOR_FOUND    |   No Vendor found  |   No vendor exists  in the system for the given vendorId| 
|500       | Server Error     |UNKNOWN      |Unknown Error   |An unknown error occurred at the server|



###Get States [GET]

+ Request ()

    + Header

            Authorization: Bearer 7z9ZeGyweG98YMAyB0iSm2EiB6bD

+ Response 200 (application/json)

    + Body
            
            [
                {
                "code": "MA",
                "value": "MA"
                },
                {
                "code": "OH",
                "value": "OH"
                },
                {
                "code": "TX",
                "value": "TX"
                }
                ]
                
                
## 12.46 Get  Additional Charges [/enumerations/additionalCharges] 

###Description

This API allows the consumer to retrieve a list of possible additional charges.

###Sample Request URL

/enumerations/additionalCharges


###Request Parameters

N/A

###Request Schema

N/A

###Sample Request Body 

GET https://api-test.enterprise.agero.com/v1/id/enumertaions/additionalCharges
Host: api-test.enterprise.agero.com

###Sample Response

HTTP/1.1 200 Ok

###Response JSON

| Schema Property|Description  |Is Required|Type|Business Rules|
|:--------------|:-------------|:----------|:---|:-------------|   
|                |              |          |KeyValuePair[ ]|

###Errors 

|HTTP Code |HTTP Reason Phrase|Error Code | Message |Reason  | 
|:---------|:----------------|:----------|:--------|:--------|
|401       |Unauthorized      |INVALID_TOKEN| oauth.v2.InvalidAccessToken: Invalid access token |A valid OAuth token was not provided| 
|404       | Resource Not Found  |  NO_VENDOR_FOUND    |   No Vendor found  |   No vendor exists  in the system for the given vendorId| 
|500       | Server Error     |UNKNOWN      |Unknown Error   |An unknown error occurred at the server|
   


###Get Additional Charges [GET]

+ Request ()

    + Header

            Authorization: Bearer 7z9ZeGyweG98YMAyB0iSm2EiB6bD

+ Response 200 (application/json)

    + Body
            
            [
                {
                "code": "W",
                "value": "Winching"
                },
                {
                "code": "L",
                "value": "Labor"
                },
                {
                "code": "G",
                "value": "Gas (fuel delivery only)"
                },
                {
                "code": "S",
                "value": "Storage"
                },
                {
                "code": "T",
                "value": "Tolls"
                },
                {
                "code": "K",
                "value": "Key Replacement"
                },
                {
                "code": "X",
                "value": "Taxes"
                },
                {
                "code": "D",
                "value": "Dollies, Skates or Go-Jacks"
                },
                {
                "code": "V",
                "value": "Disconnect Driveshaft"
                },
                {
                "code": "F",
                "value": "Ferry Charges"
                },
                {
                "code": "K",
                "value": "Key Replacement"
                },
                {
                "code": "A",
                "value": "Accident Cleanup"
                }
                ]
                
                
## 12.47 Get Days of Week [/enumerations/daysOfWeek] 

###Description

This API allows the consumer to retrieve a list of possible days of week.

###Sample Request URL

/enumerations/daysOfWeek


###Request Parameters

N/A

###Request Schema

N/A

###Sample Request Body 

GET https://api-test.enterprise.agero.com/v1/id/enumertaions/daysOfWeek
Host: api-test.enterprise.agero.com  

###Sample Response

HTTP/1.1 200 Ok

###Response JSON

| Schema Property|Description  |Is Required|Type|Business Rules|
|:--------------|:-------------|:----------|:---|:-------------|   
|                |              |          |KeyValuePair[ ]|
    
###Errors 

|HTTP Code |HTTP Reason Phrase|Error Code | Message |Reason  | 
|:---------|:----------------|:----------|:--------|:--------|
|401       |Unauthorized      |INVALID_TOKEN| oauth.v2.InvalidAccessToken: Invalid access token |A valid OAuth token was not provided| 
|404       | Resource Not Found  |  NO_VENDOR_FOUND    |   No Vendor found  |   No vendor exists  in the system for the given vendorId| 
|500       | Server Error     |UNKNOWN      |Unknown Error   |An unknown error occurred at the server|



###Get Days of Week [GET]

+ Request ()

    + Header

            Authorization: Bearer 7z9ZeGyweG98YMAyB0iSm2EiB6bD

+ Response 200 (application/json)

    + Body
            
            [
                {
                "code": "Sunday",
                "value": "Sunday"
                },
                {
                "code": "Monday",
                "value": "Monday"
                },
                {
                "code": "Tuesday",
                "value": "Tuesday"
                },
                {
                "code": "Wednesday",
                "value": "Wednesday"
                },
                {
                "code": "Thursday",
                "value": "Thursday"
                },
                {
                "code": "Friday",
                "value": "Friday"
                },
                {
                "code": "Saturday",
                "value": "Saturday"
                }
                ]   
                
##Get Performance Data [/Vendors/{VendorId}/PerformanceData?StartDate={StartDate}&EndDate={EndDate}&Offset={Offset}]

###Description

Allows the consumer to retrieve a Vendor’sPerformance data for a given service date range

###URL(s) 

- BasePath/Vendors/{VendorId}/PerformanceData?StartDate={StartDate}&EndDate={EndDate}&Offset={Offset}

###Extended Header Parameters 

n/a

###Request Path Parameters 

VendorId---Unique identifier of a Service Provider

###Request Query Parameters 

StartDate---represents the start date of the date range in mm-dd-yyyy format. 

EndDate--- represents the end date of the date range in mm-dd-yyyy format. 

Offset---indicates the starting position of the records to be returned. Offset is
set to 0 by default if it is not provided

###Request Body Type 

n/a

###Response Body Type 

PerformanceDataResponse

###Response Codes

    HTTP 200 : Ok
    HTTP 400 : Bad Request 
    HTTP 401 : Unauthorized 
    HTTP 403 : Forbidden 
    HTTP 404 : Not Found 
    HTTP 405 : Not Allowed 
    HTTP 500 : Internal Server Error 
    HTTP 501 : Service Unavailable Sample Request

###Get Performance Data [GET]
+ Request ()

    + Header
    
            x-OAuthToken: oT6UzhzKAHm6glHiV8uAcRweMuUE
            Accept: application/json

+ Response 200 (application/json)

    + Body
    
            { 
                "count": 4204, 
                "performanceData": 
                [ 
                { 
                    "vendorID": "98765", 
                    "serviceDate": "2012-09-01T00:28:00", 
                    "poNumber": "786143389", 
                    "zipcode": "786143389", 
                    "serviceCategory": "Other", 
                    "serviceEquipment": "Winch Light Duty", 
                    "etaMinutes": "60", 
                    "etaMet": "N/A", 
                    "costOfClaim": "12.00", 
                    "surveyScore": "N/A", 
                    "callAcceptance": "Accepted", 
                    "callDetail": "GOA", 
                    "territory": "Non-Assigned" 
                }, 
                { 
                    "vendorID": "98765", 
                    "serviceDate": "2012-09-01T08:02:00", 
                    "poNumber": "504057618", 
                    "zipcode": "504057618", 
                    "serviceCategory": "Light Duty Tow", 
                    "serviceEquipment": "Light Duty Flatbed", 
                    "etaMinutes": "1", 
                    "etaMet": "N/A", 
                    "costOfClaim": "52.00", 
                    "surveyScore": "N/A", 
                    "callAcceptance": "Accepted", 
                    "callDetail": "", 
                    "territory": "Non-Assigned" 
                } 
                ] 
            }
